ALTER TABLE agents ADD COLUMN temperature_enabled BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE agents ADD COLUMN top_p_enabled BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE agents ADD COLUMN top_k_enabled BOOLEAN NOT NULL DEFAULT 0;
