import { getIn, setIn } from './state'
import type { BuilderConfig } from './types'

export interface Preset {
  id: string
  label: string
  config: BuilderConfig
}

export const presets: Preset[] = [
  {
    id: 'default',
    label: 'Default',
    config: {
      chatWindow: {
        defaults: { primaryColor: 'blue', colorScheme: 'light' },
        header: { title: { title: 'Assistant', showOnlineSubtitle: true } },
      },
    },
  },
  {
    id: 'minimal',
    label: 'Minimal',
    config: {
      chatWindow: {
        defaults: { primaryColor: 'dark', colorScheme: 'light', messageRadius: 'sm' },
        header: { title: { title: 'Chat', showOnlineSubtitle: false } },
        disallowExpand: true,
        hideAssistantMessageAvatar: true,
        hideUserMessageAvatar: true,
      },
      homeScreenConfig: { bgColor: { type: 'plain' }, sendUsAMessageConfig: { title: 'Message us' } },
    },
  },
  {
    id: 'support',
    label: 'Support bot',
    config: {
      chatWindow: {
        defaults: { primaryColor: 'teal', colorScheme: 'light', messageRadius: 'lg' },
        header: { title: { title: 'Support', showOnlineSubtitle: true } },
        welcomeMessage: { message: 'Hi! How can we help you today?', infoText: 'Replies are generated by AI.' },
      },
      homeScreenConfig: {
        heading: 'Hi there 👋',
        heading2: 'How can we help?',
        sendUsAMessageConfig: { title: 'Ask our assistant', description: 'We usually reply instantly' },
      },
    },
  },
  {
    id: 'dark',
    label: 'Dark',
    config: {
      chatWindow: {
        defaults: { primaryColor: 'violet', colorScheme: 'dark', messageRadius: 'md' },
        header: { title: { title: 'Assistant', showOnlineSubtitle: true } },
      },
      homeScreenConfig: { bgColor: { type: 'default' } },
    },
  },
]

/** Branding the user typed in (name, avatars, logos) survives switching presets. */
const BRANDING_PATHS = [
  'chatWindow.header.title.title',
  'chatWindow.header.avatars',
  'homeScreenConfig.avatars',
  'homeScreenConfig.logoUrl',
  'homeScreenConfig.logoUrlDark',
]

export function applyPreset(preset: Preset, current: BuilderConfig): BuilderConfig {
  let next: BuilderConfig = structuredClone(preset.config)
  for (const path of BRANDING_PATHS) {
    const value = getIn(current, path)
    if (value !== undefined) next = setIn(next, path, structuredClone(value))
  }
  return next
}
