/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with username and password. Sets an HttpOnly session cookie on success.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description End the current session. Clears the session cookie.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Get the currently authenticated user.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth status
         * @description Check whether authentication is required for this instance.
         */
        get: operations["getAuthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/provider-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List provider types
         * @description List metadata about all supported provider types for dynamic UI rendering.
         */
        get: operations["listProviderTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List providers
         * @description List all configured providers.
         */
        get: operations["listProviders"];
        put?: never;
        /**
         * Create provider
         * @description Create a new provider configuration.
         */
        post: operations["createProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get provider
         * @description Get a single provider by ID.
         */
        get: operations["getProvider"];
        /**
         * Update provider
         * @description Update an existing provider configuration.
         */
        put: operations["updateProvider"];
        post?: never;
        /**
         * Delete provider
         * @description Delete a provider configuration.
         */
        delete: operations["deleteProvider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/providers/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test provider connectivity
         * @description Test provider connectivity by making a lightweight API call.
         */
        post: operations["testProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Liveness probe. Returns 200 if the server process is running.
         */
        get: operations["Health_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Readiness probe. Returns 200 if the server is ready to accept traffic.
         */
        get: operations["Health_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Anthropic provider config (no extra fields needed). */
        "Models.AnthropicProviderConfig": Record<string, never>;
        /** @description Response indicating whether authentication is required. */
        "Models.AuthStatusResponse": {
            /** @description True if AUTH_CREDENTIALS is configured and non-empty. */
            required: boolean;
        };
        /** @description Azure AI Foundry provider config (no extra fields needed, uses base_url for endpoint and api_key). */
        "Models.AzureAIFoundryProviderConfig": Record<string, never>;
        /** @description Azure OpenAI provider config. */
        "Models.AzureOpenAIProviderConfig": {
            /** @description Azure deployment name. */
            deploymentName: string;
            /** @description Azure API version (e.g. "2024-10-21"). */
            apiVersion: string;
        };
        /** @description AWS Bedrock provider config. */
        "Models.BedrockProviderConfig": {
            /** @description AWS region (e.g. "us-east-1"). */
            region: string;
            /** @description AWS access key ID. */
            accessKeyId: string;
            /** @description AWS secret access key. */
            secretAccessKey: string;
            /** @description AWS session token (optional). */
            sessionToken?: string;
        };
        /** @description Describes a config field for a provider type. */
        "Models.ConfigFieldInfo": {
            /** @description Field name (key in config object). */
            name: string;
            /** @description Human-readable label. */
            label: string;
            /** @description Whether this field is required. */
            required: boolean;
            /** @description Placeholder text for UI. */
            placeholder?: string;
            /** @description Whether the field contains sensitive data. */
            sensitive?: boolean;
        };
        /** @description Request to create a new provider configuration. */
        "Models.CreateProviderRequest": {
            /** @description Display name for this provider. */
            name: string;
            /** @description The provider type. */
            providerType: components["schemas"]["Models.ProviderType"];
            /** @description Full API key (stored securely, returned masked). Optional for providers that don't use API keys. */
            apiKey?: string;
            /** @description Optional base URL override. */
            baseUrl?: string;
            /** @description Provider-specific configuration. */
            config?: {
                [key: string]: string;
            };
        };
        /** @description DeepSeek provider config (no extra fields needed). */
        "Models.DeepSeekProviderConfig": Record<string, never>;
        /** @description Standard error response. */
        "Models.ErrorResponse": {
            /** @description Human-readable error description. */
            error: string;
        };
        /** @description Google AI provider config (no extra fields needed). */
        "Models.GoogleAIProviderConfig": Record<string, never>;
        /** @description Response body for health check endpoints. */
        "Models.HealthCheckResponse": {
            /** @description Current status of the probe. */
            status: components["schemas"]["Models.HealthStatus"];
            /** @description Human-readable description of the check result. */
            message: string;
        };
        /**
         * @description Status of a health check probe.
         * @enum {string}
         */
        "Models.HealthStatus": "up" | "down";
        /** @description Request body for the login endpoint. */
        "Models.LoginRequest": {
            /** @description Username to authenticate with. */
            username: string;
            /** @description Plaintext password. */
            password: string;
        };
        /** @description Response after successful login. */
        "Models.LoginResponse": {
            /** @description Authenticated username. */
            username: string;
        };
        /** @description Response after successful logout. */
        "Models.LogoutResponse": {
            ok: boolean;
        };
        /** @description Current authenticated user info. */
        "Models.MeResponse": {
            /** @description Username of the currently authenticated user. */
            username: string;
        };
        /** @description Ollama provider config (no extra fields needed, uses base_url). */
        "Models.OllamaProviderConfig": Record<string, never>;
        /** @description OpenAI-compatible provider config (no extra fields needed, uses base_url and api_key). */
        "Models.OpenAICompatibleProviderConfig": Record<string, never>;
        /** @description OpenAI provider config (no extra fields needed). */
        "Models.OpenAIProviderConfig": Record<string, never>;
        /** @description List of configured providers. */
        "Models.ProviderListResponse": {
            /** @description Array of provider configurations. */
            providers: components["schemas"]["Models.ProviderResponse"][];
        };
        /** @description A configured LLM provider with masked API key. */
        "Models.ProviderResponse": {
            /** @description Unique provider ID. */
            id: string;
            /** @description Display name for this provider configuration. */
            name: string;
            /** @description The provider type. */
            providerType: components["schemas"]["Models.ProviderType"];
            /** @description Masked API key (last 4 characters visible). Null if provider does not use an API key. */
            apiKey?: string;
            /** @description Optional base URL override (e.g. for OpenAI-compatible proxies). */
            baseUrl?: string;
            /** @description Provider-specific configuration as a JSON object. */
            config?: {
                [key: string]: string;
            };
            /** @description Whether this provider is enabled. */
            enabled: boolean;
            /**
             * Format: date-time
             * @description When this provider was created.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When this provider was last updated.
             */
            updatedAt: string;
        };
        /**
         * @description Supported LLM provider types.
         * @enum {string}
         */
        "Models.ProviderType": "google_ai" | "vertex_ai" | "openai" | "anthropic" | "ollama" | "xai" | "deepseek" | "azure_openai" | "bedrock" | "azure_ai_foundry" | "openai_compatible";
        /** @description Metadata about a provider type for dynamic UI rendering. */
        "Models.ProviderTypeInfo": {
            /** @description The provider type identifier. */
            type: components["schemas"]["Models.ProviderType"];
            /** @description Human-readable display name. */
            displayName: string;
            /** @description Whether this provider type requires an API key. */
            requiresApiKey: boolean;
            /** @description Whether this provider type requires a base URL. */
            requiresBaseUrl: boolean;
            /** @description Config fields specific to this provider type. */
            configFields: components["schemas"]["Models.ConfigFieldInfo"][];
            /** @description Hint about which environment variable to set. */
            envVarHint: string;
            /** @description Model name prefix used by Genkit. */
            modelPrefix: string;
            /** @description Default base URL if applicable. */
            baseUrlDefault?: string;
            /** @description True if this provider is not yet fully supported. */
            comingSoon?: boolean;
        };
        /** @description List of provider type metadata. */
        "Models.ProviderTypeListResponse": {
            /** @description Array of provider type information. */
            providerTypes: components["schemas"]["Models.ProviderTypeInfo"][];
        };
        /** @description Result of testing provider connectivity. */
        "Models.TestProviderResponse": {
            /** @description Whether the connection test succeeded. */
            success: boolean;
            /** @description Human-readable result message. */
            message: string;
        };
        /** @description Request to update an existing provider configuration. */
        "Models.UpdateProviderRequest": {
            /** @description Updated display name. */
            name?: string;
            /** @description New API key (leave blank to keep existing). */
            apiKey?: string;
            /** @description Updated base URL. */
            baseUrl?: string;
            /** @description Provider-specific configuration (replaces existing). */
            config?: {
                [key: string]: string;
            };
            /** @description Enable or disable this provider. */
            enabled?: boolean;
        };
        /** @description Vertex AI provider config. */
        "Models.VertexAIProviderConfig": {
            /** @description GCP project ID. */
            project: string;
            /** @description GCP region (e.g. "us-central1"). */
            location: string;
        };
        /** @description xAI provider config (no extra fields needed). */
        "Models.XAIProviderConfig": Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Models.LoginRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.LoginResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
            /** @description Client error */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.LogoutResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.MeResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    getAuthStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.AuthStatusResponse"];
                };
            };
        };
    };
    listProviderTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ProviderTypeListResponse"];
                };
            };
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ProviderListResponse"];
                };
            };
        };
    };
    createProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Models.CreateProviderRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ProviderResponse"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    getProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ProviderResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    updateProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Models.UpdateProviderRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ProviderResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    deleteProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    testProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.TestProviderResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    Health_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.HealthCheckResponse"];
                };
            };
        };
    };
    Health_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.HealthCheckResponse"];
                };
            };
            /** @description Service unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.HealthCheckResponse"];
                };
            };
        };
    };
}
