/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with username and password. Sets an HttpOnly session cookie on success.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description End the current session. Clears the session cookie.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Get the currently authenticated user.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth status
         * @description Check whether authentication is required for this instance.
         */
        get: operations["getAuthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List agents
         * @description List all agents with pagination.
         */
        get: operations["listAgents"];
        put?: never;
        /**
         * Create agent
         * @description Create a new agent.
         */
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agentId}/playground/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Playground chat
         * @description Send a message and receive a streaming response (SSE).
         */
        post: operations["playgroundChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agentId}/playground/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List playground sessions
         * @description List all playground sessions for an agent.
         */
        get: operations["listPlaygroundSessions"];
        put?: never;
        /**
         * Create playground session
         * @description Create a new playground session for an agent.
         */
        post: operations["createPlaygroundSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agentId}/playground/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete playground session
         * @description Delete a playground session.
         */
        delete: operations["deletePlaygroundSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agentId}/playground/sessions/{sessionId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List playground messages
         * @description Get all messages in a playground session.
         */
        get: operations["listPlaygroundMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get agent
         * @description Get a single agent by ID.
         */
        get: operations["getAgent"];
        /**
         * Update agent
         * @description Update an existing agent.
         */
        put: operations["updateAgent"];
        post?: never;
        /**
         * Delete agent
         * @description Delete an agent.
         */
        delete: operations["deleteAgent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List prompts
         * @description List all prompts with pagination.
         */
        get: operations["listPrompts"];
        put?: never;
        /**
         * Create prompt
         * @description Create a new prompt.
         */
        post: operations["createPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prompts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get prompt
         * @description Get a single prompt by ID.
         */
        get: operations["getPrompt"];
        /**
         * Update prompt
         * @description Update an existing prompt.
         */
        put: operations["updatePrompt"];
        post?: never;
        /**
         * Delete prompt
         * @description Delete a prompt.
         */
        delete: operations["deletePrompt"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/provider-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List provider types
         * @description List metadata about all supported provider types for dynamic UI rendering.
         */
        get: operations["listProviderTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List providers
         * @description List all configured providers.
         */
        get: operations["listProviders"];
        put?: never;
        /**
         * Create provider
         * @description Create a new provider configuration.
         */
        post: operations["createProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get provider
         * @description Get a single provider by ID.
         */
        get: operations["getProvider"];
        /**
         * Update provider
         * @description Update an existing provider configuration.
         */
        put: operations["updateProvider"];
        post?: never;
        /**
         * Delete provider
         * @description Delete a provider configuration.
         */
        delete: operations["deleteProvider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/providers/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test provider connectivity
         * @description Test provider connectivity by making a lightweight API call.
         */
        post: operations["testProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Liveness probe. Returns 200 if the server process is running.
         */
        get: operations["Health_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Readiness probe. Returns 200 if the server is ready to accept traffic.
         */
        get: operations["Health_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Paginated list of agents. */
        "Models.AgentListResponse": {
            /** @description Array of agents. */
            agents: components["schemas"]["Models.AgentResponse"][];
            /**
             * Format: int32
             * @description Total number of agents.
             */
            total: number;
            /**
             * Format: int32
             * @description Number of agents per page.
             */
            limit: number;
            /**
             * Format: int32
             * @description Number of agents skipped.
             */
            offset: number;
        };
        /** @description An AI agent configuration. */
        "Models.AgentResponse": {
            /** @description Unique agent ID. */
            id: string;
            /** @description Display name for this agent. */
            name: string;
            /** @description ID of the provider this agent uses. */
            providerId: string;
            /** @description Resolved display name of the provider. */
            providerName: string;
            /** @description Resolved type of the provider. */
            providerType: components["schemas"]["Models.ProviderType"];
            /** @description Model identifier (e.g. gemini-2.5-flash, gpt-4o). */
            modelId: string;
            /** @description ID of the system prompt, if any. */
            systemPromptId?: string;
            /** @description Resolved name of the system prompt, if any. */
            systemPromptName?: string;
            /**
             * Format: float
             * @description Sampling temperature.
             */
            temperature: number;
            /**
             * Format: float
             * @description Nucleus sampling (top-p).
             */
            topP: number;
            /**
             * Format: int32
             * @description Top-k sampling.
             */
            topK: number;
            /**
             * Format: date-time
             * @description When this agent was created.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When this agent was last updated.
             */
            updatedAt: string;
        };
        /** @description Anthropic provider config (no extra fields needed). */
        "Models.AnthropicProviderConfig": Record<string, never>;
        /** @description Response indicating whether authentication is required. */
        "Models.AuthStatusResponse": {
            /** @description True if AUTH_CREDENTIALS is configured and non-empty. */
            required: boolean;
        };
        /** @description Azure AI Foundry provider config (no extra fields needed, uses base_url for endpoint and api_key). */
        "Models.AzureAIFoundryProviderConfig": Record<string, never>;
        /** @description Azure OpenAI provider config. */
        "Models.AzureOpenAIProviderConfig": {
            /** @description Azure deployment name. */
            deploymentName: string;
            /** @description Azure API version (e.g. "2024-10-21"). */
            apiVersion: string;
        };
        /** @description AWS Bedrock provider config. */
        "Models.BedrockProviderConfig": {
            /** @description AWS region (e.g. "us-east-1"). */
            region: string;
            /** @description AWS access key ID. */
            accessKeyId: string;
            /** @description AWS secret access key. */
            secretAccessKey: string;
            /** @description AWS session token (optional). */
            sessionToken?: string;
        };
        /** @description Describes a config field for a provider type. */
        "Models.ConfigFieldInfo": {
            /** @description Field name (key in config object). */
            name: string;
            /** @description Human-readable label. */
            label: string;
            /** @description Whether this field is required. */
            required: boolean;
            /** @description Placeholder text for UI. */
            placeholder?: string;
            /** @description Whether the field contains sensitive data. */
            sensitive?: boolean;
        };
        /** @description Request to create a new agent. */
        "Models.CreateAgentRequest": {
            /** @description Display name for this agent. */
            name: string;
            /** @description ID of the provider to use. */
            providerId: string;
            /** @description Model identifier. */
            modelId: string;
            /** @description ID of an existing system prompt (optional). */
            systemPromptId?: string;
            /**
             * Format: float
             * @description Sampling temperature (default 0.95).
             */
            temperature?: number;
            /**
             * Format: float
             * @description Nucleus sampling top-p (default 0.95).
             */
            topP?: number;
            /**
             * Format: int32
             * @description Top-k sampling (default 40).
             */
            topK?: number;
        };
        /** @description Request to create a new playground session. */
        "Models.CreatePlaygroundSessionRequest": {
            /** @description Optional title for the session. */
            title?: string;
        };
        /** @description Request to create a new prompt. */
        "Models.CreatePromptRequest": {
            /** @description Display name for this prompt. */
            name: string;
            /** @description Prompt content in markdown format. */
            content: string;
        };
        /** @description Request to create a new provider configuration. */
        "Models.CreateProviderRequest": {
            /** @description Display name for this provider. */
            name: string;
            /** @description The provider type. */
            providerType: components["schemas"]["Models.ProviderType"];
            /** @description Full API key (stored securely, returned masked). Optional for providers that don't use API keys. */
            apiKey?: string;
            /** @description Optional base URL override. */
            baseUrl?: string;
            /** @description Provider-specific configuration. */
            config?: {
                [key: string]: string;
            };
        };
        /** @description DeepSeek provider config (no extra fields needed). */
        "Models.DeepSeekProviderConfig": Record<string, never>;
        /** @description Standard error response. */
        "Models.ErrorResponse": {
            /** @description Human-readable error description. */
            error: string;
        };
        /** @description Google AI provider config (no extra fields needed). */
        "Models.GoogleAIProviderConfig": Record<string, never>;
        /** @description Response body for health check endpoints. */
        "Models.HealthCheckResponse": {
            /** @description Current status of the probe. */
            status: components["schemas"]["Models.HealthStatus"];
            /** @description Human-readable description of the check result. */
            message: string;
        };
        /**
         * @description Status of a health check probe.
         * @enum {string}
         */
        "Models.HealthStatus": "up" | "down";
        /** @description Request body for the login endpoint. */
        "Models.LoginRequest": {
            /** @description Username to authenticate with. */
            username: string;
            /** @description Plaintext password. */
            password: string;
        };
        /** @description Response after successful login. */
        "Models.LoginResponse": {
            /** @description Authenticated username. */
            username: string;
        };
        /** @description Response after successful logout. */
        "Models.LogoutResponse": {
            ok: boolean;
        };
        /** @description Current authenticated user info. */
        "Models.MeResponse": {
            /** @description Username of the currently authenticated user. */
            username: string;
        };
        /** @description Ollama provider config (no extra fields needed, uses base_url). */
        "Models.OllamaProviderConfig": Record<string, never>;
        /** @description OpenAI-compatible provider config. */
        "Models.OpenAICompatibleProviderConfig": {
            /** @description Organization ID (e.g. for OpenAI org routing). */
            organization?: string;
            /** @description Custom headers as a JSON-encoded key-value object. */
            customHeaders?: string;
        };
        /** @description OpenAI provider config (no extra fields needed). */
        "Models.OpenAIProviderConfig": Record<string, never>;
        /** @description Request to send a chat message in the playground. */
        "Models.PlaygroundChatRequest": {
            /** @description The session to send the message in. */
            sessionId: string;
            /** @description The user message content. */
            content: string;
            /** @description Optional provider override for testing. */
            providerId?: string;
            /** @description Optional model override for testing. */
            modelId?: string;
            /** @description Optional system prompt override for testing. */
            systemPromptId?: string;
            /**
             * Format: float
             * @description Optional temperature override for testing.
             */
            temperature?: number;
            /**
             * Format: float
             * @description Optional top-p override for testing.
             */
            topP?: number;
            /**
             * Format: int32
             * @description Optional top-k override for testing.
             */
            topK?: number;
        };
        /** @description List of messages in a session. */
        "Models.PlaygroundMessageListResponse": {
            /** @description Array of messages. */
            messages: components["schemas"]["Models.PlaygroundMessageResponse"][];
        };
        /** @description A single message in a playground session. */
        "Models.PlaygroundMessageResponse": {
            /** @description Unique message ID. */
            id: string;
            /** @description Session this message belongs to. */
            sessionId: string;
            /**
             * @description Message role.
             * @enum {string}
             */
            role: "user" | "assistant";
            /** @description Message text content. */
            content: string;
            /**
             * Format: date-time
             * @description When this message was created.
             */
            createdAt: string;
        };
        /** @description List of playground sessions. */
        "Models.PlaygroundSessionListResponse": {
            /** @description Array of sessions. */
            sessions: components["schemas"]["Models.PlaygroundSessionResponse"][];
        };
        /** @description A playground chat session for testing an agent. */
        "Models.PlaygroundSessionResponse": {
            /** @description Unique session ID. */
            id: string;
            /** @description ID of the agent this session belongs to. */
            agentId: string;
            /** @description Session title (auto-generated from first message). */
            title: string;
            /**
             * Format: date-time
             * @description When this session was created.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When this session was last updated.
             */
            updatedAt: string;
        };
        /** @description Paginated list of prompts. */
        "Models.PromptListResponse": {
            /** @description Array of prompts. */
            prompts: components["schemas"]["Models.PromptResponse"][];
            /**
             * Format: int32
             * @description Total number of prompts.
             */
            total: number;
            /**
             * Format: int32
             * @description Number of prompts per page.
             */
            limit: number;
            /**
             * Format: int32
             * @description Number of prompts skipped.
             */
            offset: number;
        };
        /** @description A prompt (system instruction) for an agent. */
        "Models.PromptResponse": {
            /** @description Unique prompt ID. */
            id: string;
            /** @description Display name for this prompt. */
            name: string;
            /** @description Prompt content in markdown format. */
            content: string;
            /**
             * Format: date-time
             * @description When this prompt was created.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When this prompt was last updated.
             */
            updatedAt: string;
        };
        /** @description List of configured providers. */
        "Models.ProviderListResponse": {
            /** @description Array of provider configurations. */
            providers: components["schemas"]["Models.ProviderResponse"][];
        };
        /** @description A configured LLM provider with masked API key. */
        "Models.ProviderResponse": {
            /** @description Unique provider ID. */
            id: string;
            /** @description Display name for this provider configuration. */
            name: string;
            /** @description The provider type. */
            providerType: components["schemas"]["Models.ProviderType"];
            /** @description Masked API key (last 4 characters visible). Null if provider does not use an API key. */
            apiKey?: string;
            /** @description Optional base URL override (e.g. for OpenAI-compatible proxies). */
            baseUrl?: string;
            /** @description Provider-specific configuration as a JSON object. */
            config?: {
                [key: string]: string;
            };
            /** @description Whether this provider is enabled. */
            enabled: boolean;
            /**
             * Format: date-time
             * @description When this provider was created.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When this provider was last updated.
             */
            updatedAt: string;
        };
        /**
         * @description Supported LLM provider types.
         * @enum {string}
         */
        "Models.ProviderType": "google_ai" | "vertex_ai" | "openai" | "anthropic" | "ollama" | "xai" | "deepseek" | "azure_openai" | "bedrock" | "azure_ai_foundry" | "openai_compatible";
        /** @description Metadata about a provider type for dynamic UI rendering. */
        "Models.ProviderTypeInfo": {
            /** @description The provider type identifier. */
            type: components["schemas"]["Models.ProviderType"];
            /** @description Human-readable display name. */
            displayName: string;
            /** @description Whether this provider type requires an API key. */
            requiresApiKey: boolean;
            /** @description Whether this provider type requires a base URL. */
            requiresBaseUrl: boolean;
            /** @description Config fields specific to this provider type. */
            configFields: components["schemas"]["Models.ConfigFieldInfo"][];
            /** @description Hint about which environment variable to set. */
            envVarHint: string;
            /** @description Model name prefix used by Genkit. */
            modelPrefix: string;
            /** @description Default base URL if applicable. */
            baseUrlDefault?: string;
            /** @description True if this provider is not yet fully supported. */
            comingSoon?: boolean;
        };
        /** @description List of provider type metadata. */
        "Models.ProviderTypeListResponse": {
            /** @description Array of provider type information. */
            providerTypes: components["schemas"]["Models.ProviderTypeInfo"][];
        };
        /** @description Result of testing provider connectivity. */
        "Models.TestProviderResponse": {
            /** @description Whether the connection test succeeded. */
            success: boolean;
            /** @description Human-readable result message. */
            message: string;
        };
        /** @description Request to update an existing agent. */
        "Models.UpdateAgentRequest": {
            /** @description Updated display name. */
            name?: string;
            /** @description Updated provider ID. */
            providerId?: string;
            /** @description Updated model identifier. */
            modelId?: string;
            /** @description Updated system prompt ID (empty string to clear). */
            systemPromptId?: string;
            /**
             * Format: float
             * @description Updated sampling temperature.
             */
            temperature?: number;
            /**
             * Format: float
             * @description Updated nucleus sampling top-p.
             */
            topP?: number;
            /**
             * Format: int32
             * @description Updated top-k sampling.
             */
            topK?: number;
        };
        /** @description Request to update an existing prompt. */
        "Models.UpdatePromptRequest": {
            /** @description Updated display name. */
            name?: string;
            /** @description Updated prompt content in markdown format. */
            content?: string;
        };
        /** @description Request to update an existing provider configuration. */
        "Models.UpdateProviderRequest": {
            /** @description Updated display name. */
            name?: string;
            /** @description New API key (leave blank to keep existing). */
            apiKey?: string;
            /** @description Updated base URL. */
            baseUrl?: string;
            /** @description Provider-specific configuration (replaces existing). */
            config?: {
                [key: string]: string;
            };
            /** @description Enable or disable this provider. */
            enabled?: boolean;
        };
        /** @description Vertex AI provider config. */
        "Models.VertexAIProviderConfig": {
            /** @description GCP project ID. */
            project: string;
            /** @description GCP region (e.g. "us-central1"). */
            location: string;
        };
        /** @description xAI provider config (no extra fields needed). */
        "Models.XAIProviderConfig": Record<string, never>;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Models.LoginRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.LoginResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
            /** @description Client error */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.LogoutResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.MeResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    getAuthStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.AuthStatusResponse"];
                };
            };
        };
    };
    listAgents: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.AgentListResponse"];
                };
            };
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Models.CreateAgentRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.AgentResponse"];
                };
            };
        };
    };
    playgroundChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Models.PlaygroundChatRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.PlaygroundMessageResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    listPlaygroundSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.PlaygroundSessionListResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    createPlaygroundSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Models.CreatePlaygroundSessionRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.PlaygroundSessionResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    deletePlaygroundSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    listPlaygroundMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.PlaygroundMessageListResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.AgentResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Models.UpdateAgentRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.AgentResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    deleteAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    listPrompts: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.PromptListResponse"];
                };
            };
        };
    };
    createPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Models.CreatePromptRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.PromptResponse"];
                };
            };
        };
    };
    getPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.PromptResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    updatePrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Models.UpdatePromptRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.PromptResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    deletePrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    listProviderTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ProviderTypeListResponse"];
                };
            };
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ProviderListResponse"];
                };
            };
        };
    };
    createProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Models.CreateProviderRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ProviderResponse"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    getProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ProviderResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    updateProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Models.UpdateProviderRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ProviderResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
            /** @description The request conflicts with the current state of the server. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    deleteProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    testProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.TestProviderResponse"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.ErrorResponse"];
                };
            };
        };
    };
    Health_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.HealthCheckResponse"];
                };
            };
        };
    };
    Health_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.HealthCheckResponse"];
                };
            };
            /** @description Service unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Models.HealthCheckResponse"];
                };
            };
        };
    };
}
