export const MODEL_OPTIONS: Record<string, string[]> = {
  google_ai: [
    "gemini-3.1-pro-preview",
    "gemini-3-flash-preview",
    "gemini-3.1-flash-lite-preview",
    "gemini-2.5-pro",
    "gemini-2.5-flash",
    "gemini-2.5-flash-lite",
  ],
  vertex_ai: [
    "gemini-3.1-pro-preview",
    "gemini-3-flash-preview",
    "gemini-3.1-flash-lite-preview",
    "gemini-2.5-pro",
    "gemini-2.5-flash",
    "gemini-2.5-flash-lite",
  ],
  openai: [
    "gpt-5.4",
    "gpt-5.4-mini",
    "gpt-5.4-nano",
    "gpt-5.3-codex",
    "gpt-4o",
    "gpt-4o-mini",
  ],
  anthropic: [
    "claude-opus-4-6",
    "claude-sonnet-4-6",
    "claude-opus-4-5-20251202",
    "claude-sonnet-4-5-20250929",
    "claude-haiku-4-5-20251001",
  ],
  xai: [
    "grok-4.20-beta",
    "grok-4-1-fast-reasoning",
    "grok-4-1-fast-non-reasoning",
    "grok-4",
    "grok-code-fast-1",
  ],
  deepseek: ["deepseek-chat", "deepseek-reasoner"],
};
